name = "solid-start-2022-09-30"
compatibility_date = "2022-09-30"

send_metrics = false

main = "./.solid/server/server.js"
# main = "./dist/server.js"
[site]
bucket= "./dist/public"

# compatibility_flags = ["streams_enable_constructors"]